name: "dbt_pca_tests"
version: "0.0.2"

require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"

vars:
  test_precision: '{{
    "10e-7" if target.name == "duckdb"
    else "10e-5" if target.name == "clickhouse"
    else "10e-7" if target.name == "snowflake"
    else "10e-7" }}'

models:
  +materialized: table
  +pre-hook:
    - '{{
      "set max_recursive_cte_evaluation_depth = 10000;" if target.name == "clickhouse"
      else "select 1"
      }}'

tests:
  +store_failures: true

profile: "dbt_pca_profile"
