name: "dbt_pca_tests"
version: "0.0.1"

require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"

vars:
  test_case_materialization: table
  test_precision: '{{ "10e-7" if target.name == "duckdb" else "10e-6" if target.name == "clickhouse" and var("materialized", "table") == "pca" else "10e-5" }}'
#  dbt_pca:
#    method_options:
#      nipals:
#        check_tol: false
#        max_iter: 300

models:
  +materialized: '{{ var("test_case_materialization", "table") }}'
  +pre-hook:
    - '{{ "set max_recursive_cte_evaluation_depth = 10000;" if target.name == "clickhouse" else "select 1" }}'

tests:
  +store_failures: true

# During dev only!
profile: "dbt_pca_profile"
