dbt_pca_profile:
  target: snowflake
  outputs:
    duckdb:
      type: duckdb
      path: dbt.duckdb
    clickhouse:
      type: clickhouse
      port: 8123
      user: dbt_user
      password: dbt_user_password
      schema: default
    snowflake:
      type: snowflake
      account: '{{ env_var("SNOWFLAKE_ACCOUNT") }}'
      user: '{{ env_var("SNOWFLAKE_USER") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'
      role: '{{ env_var("SNOWFLAKE_ROLE") }}'
      warehouse: '{{ env_var("SNOWFLAKE_WAREHOUSE") }}'
      database: '{{ env_var("SNOWFLAKE_DATABASE") }}'
      schema: '{{ env_var("SNOWFLAKE_SCHEMA") }}'
