name: tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:

  pre-commit:
    name: Pre-Commit Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - uses: pre-commit/action@576ff52938d158a24ac7e009dfa94b1455e7df99

  integration-tests-duckdb:
    name: Integration Tests - Duckdb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install
          chmod +x ./run
          uv venv
          uv sync --extra python-dev --extra duckdb
        env:
          UV_NO_SYNC: true
          DO_NOT_TRACK: 1
      - name: Test
        run: ./run test duckdb
        env:
          UV_NO_SYNC: true
          DO_NOT_TRACK: 1

  integration-tests-clickhouse:
    name: Integration Tests - Clickhouse
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:latest
        env:
          CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
          CLICKHOUSE_PASSWORD: dbt_user_password
          CLICKHOUSE_USER: dbt_user
          CLICKHOUSE_DB: default
        ports:
          - 8123:8123
          - 9000:9000
        options: >-
          --ulimit nofile=262144:262144
          --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install
          chmod +x ./run
          uv venv
          uv sync --extra python-dev --extra clickhouse
        env:
          UV_NO_SYNC: true
          DO_NOT_TRACK: 1
      - name: Test
        run: ./run test clickhouse
        env:
          UV_NO_SYNC: true
          DO_NOT_TRACK: 1
