name: tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:

  prek:
    name: Prek Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0

  integration-tests-duckdb:
    name: Integration Tests - Duckdb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install
          chmod +x ./run
          uv sync --group dev
        env:
          UV_NO_SYNC: true
          DO_NOT_TRACK: 1
      - name: Test
        run: ./run test duckdb
        env:
          UV_NO_SYNC: true
          DO_NOT_TRACK: 1

  integration-tests-clickhouse:
    name: Integration Tests - Clickhouse
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:24.10
        env:
          CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
          CLICKHOUSE_PASSWORD: dbt_user_password
          CLICKHOUSE_USER: dbt_user
          CLICKHOUSE_DB: default
        ports:
          - 8123:8123
          - 9000:9000
        options: >-
          --ulimit nofile=262144:262144
          --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install
          chmod +x ./run
          uv sync --group dev
        env:
          UV_NO_SYNC: true
          DO_NOT_TRACK: 1
      - name: Test
        run: ./run test clickhouse
        env:
          UV_NO_SYNC: true
          DO_NOT_TRACK: 1
